#!/bin/zsh
file=${1:-a.cpp}
#time g++ -D ARYANC403=1 -D LOCAL=1 ${file} -fsanitize=address,undefined,signed-integer-overflow -Wall -std=gnu++17 #&& time ./${file}.exe ${2}
time g++ -DARYANC403 -DLOCAL -DHOME ${file} -o ${file}.exe -fsanitize=address,undefined,signed-integer-overflow -Wall -std=gnu++17 && time ./${file}.exe ${2}
