#!/bin/zsh
file=${1:-a.cpp}
g++ -D ARYANC403=1 -D LOCAL=1 ${file} -o ${file}.exe -fsanitize=address,undefined,signed-integer-overflow -Wall -Wextra -O2 -Wfloat-equal -Wconversion -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2  -std=gnu++17 && time ./${file}.exe ${2}
